import { useState } from "react";
import {
  data,
  useLoaderData,
  useParams,
  type ShouldRevalidateFunctionArgs,
} from "react-router";
import { MfeMount } from "../components/MfeMount";
import { mfe1Base } from "../mfeConfig";
import { MFE1_FRAGMENT_URL, MFE_SSR_TIMEOUT_MS } from "../mfeConfig.server";
import { peekHtml, putHtml } from "../mfeHtmlStore";
import type { MfeCapabilities } from "../mfeCapabilities";
import {
  isCompatible,
  type FragmentRequest,
  type FragmentResponse,
} from "@platform/mfe-contract";
// Generated by the plugin from routes.ts + this module's own exports, so the
// arg types follow React Router's version rather than being restated here.
import type { Route } from "./+types/mfe1";

// Both halves of the contract come from @platform/mfe-contract, which every
// MFE implements. Each side also reports the contract version it was built
// against, checked below before its output is used: shell and MFEs deploy
// independently, so compiling against the same types doesn't mean running
// against them.

/** `mfe1/capabilities` — declared once, in the map every MFE shares. */
type Mfe1Capabilities = MfeCapabilities["mfe1"];

/**
 * Fetches a rendered fragment from an MFE's server.
 *
 * The MFE runs in its own process, so a failure here is an ordinary rejected
 * promise or a non-2xx response — never something that can corrupt or crash
 * the shell. `AbortSignal.timeout` also genuinely cancels the request, unlike
 * racing a timer against in-process work.
 */
async function fetchFragment(
  endpoint: string,
  input: FragmentRequest,
): Promise<FragmentResponse> {
  const response = await fetch(endpoint, {
    method: "POST",
    headers: { "content-type": "application/json" },
    body: JSON.stringify(input),
    signal: AbortSignal.timeout(MFE_SSR_TIMEOUT_MS),
  });

  if (!response.ok) {
    throw new Error(`${endpoint} responded ${response.status}`);
  }

  const fragment = (await response.json()) as FragmentResponse;
  // A fragment server on another contract major: its markup or data may not
  // be what this shell expects. Treated like any failure — client rendering.
  if (!isCompatible(fragment.contractVersion)) {
    throw new Error(
      `${endpoint} speaks contract v${fragment.contractVersion}, this shell doesn't`,
    );
  }
  return fragment;
}

// In framework mode `loader` is server-only by construction — React Router
// strips it from the client bundle.
export async function loader({ request, params, url }: Route.LoaderArgs) {
  // `url`, not `request.url`: on a client-side navigation the request is
  // React Router's `/fr/mfe1/about.data?_routes=…`; `url` has that stripped.
  // Forwarding the raw one made MFE1 match `/about.data` and answer 404.
  const { locale } = params;

  try {
    const result = await fetchFragment(MFE1_FRAGMENT_URL, {
      url: url.pathname + url.search,
      headers: Object.fromEntries(request.headers.entries()),
      basePath: mfe1Base(locale),
      context: { locale },
    });

    // `html` deliberately does NOT go into loader data — only a token does.
    // `data` and `head` do: the MFE's client router needs `data` to hydrate
    // without refetching, and both are small.
    return data(
      {
        data: result.data,
        head: result.head,
        htmlToken: putHtml(result.html),
      },
      { status: result.status },
    );
  } catch (error) {
    // The MFE is a fragment, not the page. A broken or slow one costs SEO for
    // that fragment and falls back to client rendering — it must never take
    // down the shell's response.
    console.error(
      "[shell] MFE1 fragment fetch failed, falling back to CSR:",
      error,
    );
    return null;
  }
}

// Navigation *within* the MFE is owned by its own router; don't re-run the
// shell loader for it (which would re-render the MFE server-side). The one
// change that is the shell's — the locale — does refetch: new loader data
// remounts the MFE below with the new `context`.
export function shouldRevalidate({
  currentParams,
  nextParams,
}: ShouldRevalidateFunctionArgs) {
  return currentParams.locale !== nextParams.locale;
}

// `Route.MetaArgs` tracks the arg's shape across React Router versions — the
// v7 → v8 `data` → `loaderData` rename would now be a compile error, not a
// silently missing title.
// The fragment's stylesheets go in the server-rendered <head> so its markup
// is styled on first paint, not only once MFE1's bundle loads its CSS.
export function meta({ loaderData }: Route.MetaArgs) {
  const head = loaderData?.head;
  return [
    ...(head?.title ? [{ title: head.title }] : []),
    ...(head?.styles ?? []).map((href) => ({
      tagName: "link" as const,
      rel: "stylesheet",
      href,
    })),
  ];
}

export default function Mfe1Route() {
  const initial = useLoaderData<typeof loader>();
  // Validated by the parent layout (routes/locale.tsx).
  const locale = useParams().locale!;
  // Resolved on the server only. On the client the container already holds the
  // server-rendered markup, so there is nothing to look up. Undefined when SSR
  // failed — the MFE then mounts client-side, exactly like a CSR-only MFE.
  const [ssrHtml] = useState(() =>
    typeof document === "undefined" && initial
      ? peekHtml(initial.htmlToken)
      : undefined,
  );
  return (
    <MfeMount
      remote="mfe1"
      basePath={mfe1Base(locale)}
      locale={locale}
      data={initial?.data}
      ssrHtml={ssrHtml}
    />
  );
}
