import { loadRemote } from "@module-federation/enhanced/runtime";
import { useEffect, useRef, useState } from "react";
import { data, useLoaderData, useLocation, useNavigate } from "react-router";
import { MFE1_BASE } from "../mfeConfig";
import { MFE1_FRAGMENT_URL, MFE_SSR_TIMEOUT_MS } from "../mfeConfig.server";
import { peekHtml, putHtml } from "../mfeHtmlStore";
import type { MfeCapabilities } from "../mfeCapabilities";
import {
  isCompatible,
  type ClientEntryHandle,
  type ClientEntryModule,
  type FragmentRequest,
  type FragmentResponse,
} from "@platform/mfe-contract";
// Generated by the plugin from routes.ts + this module's own exports, so the
// arg types follow React Router's version rather than being restated here.
import type { Route } from "./+types/mfe1";

// Both halves of the contract come from @platform/mfe-contract, which every
// MFE implements. Each side also reports the contract version it was built
// against, checked below before its output is used: shell and MFEs deploy
// independently, so compiling against the same types doesn't mean running
// against them.

/** `mfe1/capabilities` — declared once, in the map every MFE shares. */
type Mfe1Capabilities = MfeCapabilities["mfe1"];

/**
 * Fetches a rendered fragment from an MFE's server.
 *
 * The MFE runs in its own process, so a failure here is an ordinary rejected
 * promise or a non-2xx response — never something that can corrupt or crash
 * the shell. `AbortSignal.timeout` also genuinely cancels the request, unlike
 * racing a timer against in-process work.
 */
async function fetchFragment(
  endpoint: string,
  input: FragmentRequest,
): Promise<FragmentResponse> {
  const response = await fetch(endpoint, {
    method: "POST",
    headers: { "content-type": "application/json" },
    body: JSON.stringify(input),
    signal: AbortSignal.timeout(MFE_SSR_TIMEOUT_MS),
  });

  if (!response.ok) {
    throw new Error(`${endpoint} responded ${response.status}`);
  }

  const fragment = (await response.json()) as FragmentResponse;
  // A fragment server on another contract major: its markup or data may not
  // be what this shell expects. Treated like any failure — client rendering.
  if (!isCompatible(fragment.contractVersion)) {
    throw new Error(
      `${endpoint} speaks contract v${fragment.contractVersion}, this shell doesn't`,
    );
  }
  return fragment;
}

// In framework mode `loader` is server-only by construction — React Router
// strips it from the client bundle.
export async function loader({ request }: Route.LoaderArgs) {
  const url = new URL(request.url);

  try {
    const result = await fetchFragment(MFE1_FRAGMENT_URL, {
      url: url.pathname + url.search,
      headers: Object.fromEntries(request.headers.entries()),
      basePath: MFE1_BASE,
    });

    // `html` deliberately does NOT go into loader data — only a token does.
    // `data` and `head` do: the MFE's client router needs `data` to hydrate
    // without refetching, and both are small.
    return data(
      {
        data: result.data,
        head: result.head,
        htmlToken: putHtml(result.html),
      },
      { status: result.status },
    );
  } catch (error) {
    // The MFE is a fragment, not the page. A broken or slow one costs SEO for
    // that fragment and falls back to client rendering — it must never take
    // down the shell's response.
    console.error(
      "[shell] MFE1 fragment fetch failed, falling back to CSR:",
      error,
    );
    return null;
  }
}

// Navigation *within* the MFE is owned by its own router; don't re-run
// the shell loader (which would re-render the MFE server-side).
export function shouldRevalidate() {
  return false;
}

// `Route.MetaArgs` tracks the arg's shape across React Router versions — the
// v7 → v8 `data` → `loaderData` rename would now be a compile error, not a
// silently missing title.
export function meta({ loaderData }: Route.MetaArgs) {
  return loaderData?.head?.title ? [{ title: loaderData.head.title }] : [];
}

export default function Mfe1Mount() {
  const initial = useLoaderData<typeof loader>();
  // Resolved on the server only. On the client the container already holds the
  // server-rendered markup, so there is nothing to look up. Null when SSR
  // failed — the container renders empty and the MFE mounts client-side.
  const [ssrHtml] = useState(() =>
    typeof document === "undefined" && initial
      ? peekHtml(initial.htmlToken)
      : undefined,
  );
  const containerRef = useRef<HTMLDivElement>(null);
  const handleRef = useRef<ClientEntryHandle | null>(null);
  const location = useLocation();
  const navigate = useNavigate();

  // Where the shell's router believes it is, readable from callbacks without
  // re-running the mount effect on every navigation.
  const href = location.pathname + location.search;
  const hrefRef = useRef(href);
  hrefRef.current = href;

  useEffect(() => {
    const container = containerRef.current;
    if (!container) return;
    // Set by the cleanup. Covers StrictMode's mount → unmount → mount in dev
    // and a real unmount racing the async load: a load that resolves after
    // cleanup must not mount into a container this route no longer owns.
    let cancelled = false;

    async function loadRemoteMfe() {
      const mfeClientModule =
        await loadRemote<ClientEntryModule>("mfe1/clientEntry");
      if (cancelled) return;
      if (!mfeClientModule) {
        throw new Error("mfe1/clientEntry unavailable (remote not registered)");
      }
      // A browser bundle on another contract major. Not mounting it leaves any
      // server markup static — visible, not interactive — rather than broken.
      if (!isCompatible(mfeClientModule.contractVersion)) {
        throw new Error(
          `mfe1/clientEntry speaks contract v${mfeClientModule.contractVersion}, this shell doesn't`,
        );
      }
      handleRef.current = mfeClientModule.clientEntry(container!, {
        data: initial?.data,
        basePath: MFE1_BASE,
        host: {
          href: hrefRef.current,
          // MFE → shell. The shell is the only writer of window.history, so an
          // in-MFE link becomes a shell navigation. `shouldRevalidate` above
          // keeps that from re-running this route's loader.
          onNavigate: (next) => {
            if (next !== hrefRef.current) void navigate(next);
          },
        },
      });
    }

    loadRemoteMfe().catch((error) => {
      console.error("[shell] MFE1 client entry failed to load:", error);
    });

    return () => {
      cancelled = true;
      // Without this the MFE's React root outlives the route: detached from
      // the DOM but still rendering.
      handleRef.current?.unmount();
      handleRef.current = null;
    };
  }, [initial, navigate]);

  // Shell → MFE. Every shell navigation — its own links, back/forward, and the
  // ones the MFE just asked for — ends here; the MFE ignores the ones it
  // already knows about. Keyed on `location.key` so a navigation to the same
  // pathname still counts.
  useEffect(() => {
    handleRef.current?.navigate(hrefRef.current);
  }, [location.key]);

  return (
    <div
      id="mfe1-root"
      ref={containerRef}
      // The container's contents are owned by MFE1, not by this React tree:
      // server-rendered here, then hydrated by MFE1's own root. React does not
      // write innerHTML during hydration, so the server markup survives the
      // client's empty value; suppressHydrationWarning silences the dev-only
      // mismatch notice for that intentional difference.
      suppressHydrationWarning
      dangerouslySetInnerHTML={{ __html: ssrHtml ?? "" }}
    />
  );
}
